name: Test Happy
description: Test
inputs:
  RUNNER_ID:
    required: false
    description: Actions Runner ID
  NAME:
    required: false
    description: Some name
  # MY_SECRET:
  #   required: false
  #   description: Some secret

runs:
  using: "composite"
  steps:
    - run: |
        echo "Runner ID: ${{ inputs.RUNNER_ID }}"
        echo "Name: ${{ inputs.NAME }}"
        echo "MY_VAR: ${MY_VAR}"
        echo "MY_SECRET: ${MY_SECRET}"
        if [ "${MY_SECRET}" == "I_AM_A_SECRET" ] ; then echo 'yes' ; else echo 'no' ; fi
        echo "done."
      shell: bash
      # env: # env not needed here?  why?
