name: More Dynamic Jobs
run-name: Test
on:
  workflow_dispatch:
    inputs:
      Go:
        required: false
        type: string

jobs:
  generate-t:
    runs-on: ubuntu-latest
    outputs:
      MATRIX_A: ${{ steps.set-MATRIX.outputs.MATRIX_A }}
      MATRIX_B: ${{ steps.set-MATRIX.outputs.MATRIX_B }}
    steps:
    - name: Build Matrix
      id: set-MATRIX
      # run: echo 'MATRIX=["abc", "def", "ghi"]' >> $GITHUB_OUTPUT
      run: |
        # out=$( echo 'MATRIX={
        #   "include": [
        #     {
        #       "bannana": [
        #         "10",
        #         "11",
        #         "12"
        #       ]
        #     },
        #     {
        #       "apple": [
        #         "A",
        #         "B",
        #         "C",
        #       ]
        #     }
        #   ]
        # }' )
        out_a=$( echo 'MATRIX_A=["abc", "def", "ghi"]' )
        out_b=$( echo 'MATRIX_B=["10", "11", "12"]' )
        echo "trying again..."
        echo "$out_a"
        echo "$out_b"
        echo "this is what we are doing."
        echo "$out_a" >> $GITHUB_OUTPUT
        echo "$out_b" >> $GITHUB_OUTPUT
  jober-t:
    needs: generate-t
    strategy:
      matrix:
        matrix_a: ${{fromJson(needs.generate-t.outputs.matrix_a)}}
        matrix_b: ${{fromJson(needs.generate-t.outputs.matrix_b)}}
      fail-fast: false
    uses: ./.github/workflows/dynamic.yml
    with:
      POWER: ${{ matrix.matrix_a }}.${{ matrix.matrix_b }}
