name: More Dynamic Jobs
run-name: Test
on:
  workflow_dispatch:
    inputs:
      Go:
        required: false
        type: string

jobs:
  generate-t:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.set-MATRIX.outputs.MATRIX }}
    steps:
    - id: set-MATRIX
      # run: echo 'MATRIX=["abc", "def", "ghi"]' >> $GITHUB_OUTPUT
      run: echo 'MATRIX=["abc":"do the thing", "def":"do more", "ghi":"do stuff"]' >> $GITHUB_OUTPUT
  jober-t:
    needs: generate-t
    strategy:
      matrix:
        something: ${{fromJson(needs.generate-t.outputs.matrix)}}
      fail-fast: false
    uses: ./.github/workflows/dynamic.yml
