name: PR Label build Reset
run-name: Build by ${{ github.actor }} (branch ${{ inputs.BRANCH }})
on:
  pull_request:
    types:
      - labeled
      - unlabeled
    branches:
      - main
      - development*
      - releases/**

jobs:
  build:
    if: github.event.label.name == 'build-reset'
    # uses: actions/checkout@v3
    #uses: ./.github/actions/happy/

    runs-on: [ubuntu-latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a command
      - name: Run happy
        id: run-happy
        uses: ./.github/actions/happy
        with:
          RUNNER_ID: run-happy
          NAME: hoard
          # MY_SECRET: ${{ secrets.MYSECRET }}
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_VAR: ${{ vars.MY_VAR }}

      # Runs a command
      - name: Run a command
        run: bash test.sh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_VAR: ${{ vars.MY_VAR }}