name: ScheduleName
run-name: Hello ${{ github.actor }} - ${{ github.event.schedule == '55 * * * *' && 'ABC' || github.event.schedule == '31 * * * *' && 'DEF' || github.event.schedule == '32 * * * *' && 'GH' || github.event.schedule == '33 * * * *' && 'IJ' || github.event.schedule == '35 * * * *' && 'LM' || github.event.schedule == '36 * * * *' && 'MM' || github.event.schedule == '30 * * * *' && 'LAST' }}  

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Scehduled run
  schedule:
    - cron:  '30 * * * *'
    - cron:  '31 * * * *'
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! ${{ github.event.schedule }}
