# This is a basic workflow to help you get started with Actions

name: ScheduleCI
run-name: Hello ${{ github.actor }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Scehduled run
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Runs at 30 minutes past the hour, every hour
    - cron:  '30 * * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a command
      - name: Run a command
        run: bash test.sh
